// <auto-generated />
using System;
using BAO_Cinemas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAO_Cinemas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312172708_InitBookingSystemFix")]
    partial class InitBookingSystemFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAO_Cinemas.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "241 Xuân Thủy, Cầu Giấy, Hà Nội",
                            Hotline = "1900 1111",
                            Name = "BAO Cinemas Cầu Giấy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bitexco, Quận 1, TP.HCM",
                            Hotline = "1900 2222",
                            Name = "BAO Cinemas Quận 1"
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = 180,
                            Genre = "Hành Động, Viễn Tưởng",
                            PosterUrl = "/images/posters/avengers_endgame.jpg",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = 148,
                            Genre = "Kinh Dị",
                            PosterUrl = "/images/posters/chao_vu_nha.jpg",
                            ReleaseDate = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chào Vũ Nhá"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Duration = 131,
                            Genre = "Tâm Lý, Tình Cảm",
                            PosterUrl = "/images/posters/mai.jpg",
                            ReleaseDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mai"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Duration = 166,
                            Genre = "Viễn Tưởng, Hành Động",
                            PosterUrl = "/images/posters/dune2.jpg",
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune: Part Two"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Duration = 115,
                            Genre = "Hành Động, Quái Vật",
                            PosterUrl = "/images/posters/godzilla_kong.jpg",
                            ReleaseDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Godzilla x Kong"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Duration = 190,
                            Genre = "Viễn Tưởng, Phiêu Lưu",
                            PosterUrl = "/images/posters/avatar3.jpg",
                            ReleaseDate = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar 3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Duration = 127,
                            Genre = "Hành Động, Hài",
                            PosterUrl = "/images/posters/deadpool.jpg",
                            ReleaseDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deadpool & Wolverine"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Duration = 94,
                            Genre = "Hoạt Hình, Hài",
                            PosterUrl = "/images/posters/kungfu_panda4.jpg",
                            ReleaseDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kung Fu Panda 4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Duration = 100,
                            Genre = "Hoạt Hình, Tâm Lý",
                            PosterUrl = "/images/posters/inside_out2.jpg",
                            ReleaseDate = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inside Out 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Duration = 120,
                            Genre = "Phiêu Lưu, Gia Đình",
                            PosterUrl = "/images/posters/mufasa.jpg",
                            ReleaseDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mufasa: The Lion King"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Duration = 180,
                            Genre = "Tiểu Sử, Lịch Sử",
                            PosterUrl = "/images/posters/oppenheimer.jpg",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer IMAX"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Duration = 169,
                            Genre = "Viễn Tưởng, Không Gian",
                            PosterUrl = "/images/posters/interstellar.jpg",
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar IMAX"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Duration = 152,
                            Genre = "Hành Động, Tội Phạm",
                            PosterUrl = "/images/posters/dark_knight.jpg",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight IMAX"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Duration = 130,
                            Genre = "Hành Động",
                            PosterUrl = "/images/posters/top_gun.jpg",
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun: Maverick IMAX"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Duration = 148,
                            Genre = "Hành Động, Viễn Tưởng",
                            PosterUrl = "/images/posters/inception.jpg",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception IMAX"
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Name = "Phòng 1 - Standard",
                            TotalSeats = 98
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Name = "Phòng 2 - IMAX",
                            TotalSeats = 98
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Name = "Phòng 1 - Standard",
                            TotalSeats = 98
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookedSeats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedSeats = "E7,E8",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 13, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 75000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 13, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookedSeats = "",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 90000.0,
                            RoomId = 2,
                            StartTime = new DateTime(2026, 3, 13, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookedSeats = "A1,A2,A3",
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 3, 13, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 100000.0,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 3, 13, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookedSeats = "",
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 3, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 75000.0,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 3, 14, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookedSeats = "G13,G14",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 13, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Price = 80000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 13, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BookedSeats = "D5,D6,D7",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 14, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Price = 85000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 14, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.HasOne("BAO_Cinemas.Models.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Showtime", b =>
                {
                    b.HasOne("BAO_Cinemas.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BAO_Cinemas.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAO_Cinemas.Models.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Cinema", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.Navigation("Showtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
