// <auto-generated />
using System;
using BAO_Cinemas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAO_Cinemas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312130359_SeedMoviesData")]
    partial class SeedMoviesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAO_Cinemas.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = 180,
                            Genre = "Hành Động, Viễn Tưởng",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Avengers",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = 148,
                            Genre = "Hành Động",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Spider-Man",
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Duration = 131,
                            Genre = "Tâm Lý, Tình Cảm",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Mai",
                            ReleaseDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mai"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Duration = 166,
                            Genre = "Viễn Tưởng, Hành Động",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Dune+2",
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune: Part Two"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Duration = 115,
                            Genre = "Hành Động, Quái Vật",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=GxK",
                            ReleaseDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Godzilla x Kong"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Duration = 190,
                            Genre = "Viễn Tưởng, Phiêu Lưu",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Avatar+3",
                            ReleaseDate = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar 3"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Duration = 127,
                            Genre = "Hành Động, Hài",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Deadpool",
                            ReleaseDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deadpool & Wolverine"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Duration = 94,
                            Genre = "Hoạt Hình, Hài",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Kung+Fu",
                            ReleaseDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kung Fu Panda 4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Duration = 100,
                            Genre = "Hoạt Hình, Tâm Lý",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Inside+Out",
                            ReleaseDate = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inside Out 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Duration = 180,
                            Genre = "Tiểu Sử, Lịch Sử",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Oppenheimer",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer IMAX"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Duration = 169,
                            Genre = "Viễn Tưởng, Không Gian",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Interstellar",
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar IMAX"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Duration = 152,
                            Genre = "Hành Động, Tội Phạm",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Dark+Knight",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight IMAX"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Duration = 130,
                            Genre = "Hành Động",
                            PosterUrl = "https://placehold.co/300x450/1a1a1a/FFF?text=Top+Gun",
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun: Maverick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
