// <auto-generated />
using System;
using BAO_Cinemas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAO_Cinemas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAO_Cinemas.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSeats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingTime = new DateTime(2026, 3, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "khach1@gmail.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "A1,A2",
                            ShowtimeId = 1,
                            TotalPrice = 150000.0
                        },
                        new
                        {
                            Id = 2,
                            BookingTime = new DateTime(2026, 3, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "khach2@gmail.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "B5,B6,B7",
                            ShowtimeId = 1,
                            TotalPrice = 225000.0
                        },
                        new
                        {
                            Id = 3,
                            BookingTime = new DateTime(2026, 3, 12, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "khach3@gmail.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "C1,C2",
                            ShowtimeId = 2,
                            TotalPrice = 180000.0
                        },
                        new
                        {
                            Id = 4,
                            BookingTime = new DateTime(2026, 3, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "khach4@gmail.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "D4",
                            ShowtimeId = 2,
                            TotalPrice = 90000.0
                        },
                        new
                        {
                            Id = 5,
                            BookingTime = new DateTime(2026, 3, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "khach5@gmail.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "E1,E2,E3,E4",
                            ShowtimeId = 1,
                            TotalPrice = 400000.0
                        },
                        new
                        {
                            Id = 6,
                            BookingTime = new DateTime(2026, 3, 14, 0, 46, 53, 0, DateTimeKind.Unspecified),
                            CustomerName = "admin@baocinemas.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "A1",
                            ShowtimeId = 10,
                            TotalPrice = 50000.0,
                            UserId = "admin-user-id-789"
                        },
                        new
                        {
                            Id = 7,
                            BookingTime = new DateTime(2026, 3, 14, 0, 52, 11, 0, DateTimeKind.Unspecified),
                            CustomerName = "admin@baocinemas.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "A1",
                            ShowtimeId = 4,
                            TotalPrice = 75000.0,
                            UserId = "admin-user-id-789"
                        },
                        new
                        {
                            Id = 8,
                            BookingTime = new DateTime(2026, 3, 14, 0, 54, 58, 0, DateTimeKind.Unspecified),
                            CustomerName = "admin@baocinemas.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "A1",
                            ShowtimeId = 12,
                            TotalPrice = 100000.0,
                            UserId = "admin-user-id-789"
                        },
                        new
                        {
                            Id = 9,
                            BookingTime = new DateTime(2026, 3, 14, 1, 22, 3, 0, DateTimeKind.Unspecified),
                            CustomerName = "doanbaongo@baocinemas.com",
                            CustomerPhone = "Không yêu cầu",
                            SelectedSeats = "E8",
                            ShowtimeId = 13,
                            TotalPrice = 75000.0,
                            UserId = "2c560b88-4178-4531-9177-11b7430c4714"
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "241 Xuân Thủy, Cầu Giấy, Hà Nội",
                            Hotline = "1900 1111",
                            Name = "BAO Cinemas Cầu Giấy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bitexco, Quận 1, TP.HCM",
                            Hotline = "1900 2222",
                            Name = "BAO Cinemas Quận 1"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ngõ 3, Phố Xốm, Hà Đông",
                            Hotline = "1900 3667",
                            Name = "BAO Cinemas Hà Đông"
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = 180,
                            Genre = "Hành Động, Viễn Tưởng",
                            PosterUrl = "/images/posters/avengers_endgame.jpg",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = 148,
                            Genre = "Kinh Dị",
                            PosterUrl = "/images/posters/chao_vu_nha.jpg",
                            ReleaseDate = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chào Vũ Nhá"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Duration = 174,
                            Genre = "Tâm Lý",
                            PosterUrl = "/images/posters/fb23d9ba-3b22-4ce5-abfe-9dc0560973f0_Kokuho.jpg",
                            ReleaseDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kokuho"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Duration = 108,
                            Genre = "Hoạt hình, Hài, Phiêu lưu",
                            PosterUrl = "/images/posters/db3e3440-c65d-4651-9b02-0f4340a666b7_Zootopia.jpg",
                            ReleaseDate = new DateTime(2016, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Zootopia"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 0,
                            Duration = 96,
                            Genre = "Hoạt hình, Phiêu lưu, Gia đình",
                            PosterUrl = "/images/posters/dbe18a3d-adbc-418d-b6bc-105c02f29d15_up.jpg",
                            ReleaseDate = new DateTime(2009, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Up"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 0,
                            Duration = 95,
                            Genre = "Hoạt hình, Phiêu lưu, Gia đình ",
                            PosterUrl = "/images/posters/a5dbc4af-ecea-4024-b259-9a62536cab00_despicable_me.jpg",
                            ReleaseDate = new DateTime(2010, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Despicable Me"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Duration = 120,
                            Genre = "Hành Động, Hoạt Hình",
                            PosterUrl = "/images/posters/1f9996b4-1960-4b42-9152-dc93bc9e9688_la_tieu_hac_chien_ky_2.jpg",
                            ReleaseDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La Tiểu Hắc Chiến Ký 2"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Duration = 157,
                            Genre = "Khoa Học Viễn Tưởng, Phiêu Lưu",
                            PosterUrl = "/images/posters/e35007eb-37a0-486c-8e49-ac82a9dabc8d_thoat_khoi_tan_the.jpg",
                            ReleaseDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thoát Khỏi Tận Thế"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Duration = 180,
                            Genre = "Hài, Kinh Dị, Tâm Lý",
                            PosterUrl = "/images/posters/7a9bab2b-4946-4f05-9653-2484e106a006_dai_tiec_trang_mau_8.jpg",
                            ReleaseDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Đại Tiệc Trăng Máu"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 0,
                            Duration = 92,
                            Genre = "Hoạt hình, Hài, Hành động",
                            PosterUrl = "/images/posters/20bb43de-a951-4595-8be7-01e317964db3_kung_fu_panda.jpg",
                            ReleaseDate = new DateTime(2008, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kung Fu Panda"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 0,
                            Duration = 100,
                            Genre = "Hoạt hình, Phiêu lưu, Gia đình",
                            PosterUrl = "/images/posters/4047f645-7d94-4543-89aa-4cb888877eed_nemo.jpg",
                            ReleaseDate = new DateTime(2003, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Finding Nemo"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Duration = 122,
                            Genre = "Hành động, Tội phạm, Giật gân",
                            PosterUrl = "/images/posters/6919d6d6-a607-4fe1-b6f2-14bb834c38ad_john_wick_2.jpg",
                            ReleaseDate = new DateTime(2017, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick: Chapter 2"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Duration = 101,
                            Genre = "Hành động, Giật gân",
                            PosterUrl = "/images/posters/d685d40f-ec80-4184-81e4-3babf6d01461_john_wick.jpg",
                            ReleaseDate = new DateTime(2014, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick: Chapter 1"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 0,
                            Duration = 131,
                            Genre = "Hành động, Tội phạm, Giật gân",
                            PosterUrl = "/images/posters/c821ada9-4298-4132-a8b1-35c772c6f54b_john_wick_3.jpg",
                            ReleaseDate = new DateTime(2019, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick: Chapter 3 – Parabellum"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 0,
                            Duration = 194,
                            Genre = "Lãng mạn, Tâm lý",
                            PosterUrl = "/images/posters/5534399c-a8ea-423e-a3ff-fe48c137c945_Titanic.jpg",
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Name = "Phòng 1 - Standard",
                            Status = 1,
                            TotalSeats = 98
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Name = "Phòng 2 - IMAX",
                            Status = 1,
                            TotalSeats = 98
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Name = "Phòng 1 - Standard",
                            Status = 1,
                            TotalSeats = 98
                        });
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookedSeats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedSeats = "",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 13, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 75000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 13, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookedSeats = "",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 90000.0,
                            RoomId = 2,
                            StartTime = new DateTime(2026, 3, 13, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookedSeats = "",
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 3, 13, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 100000.0,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 3, 13, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookedSeats = "A1",
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 3, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 75000.0,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 3, 14, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BookedSeats = "A1",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 18, 8, 43, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Price = 50000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 18, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BookedSeats = "",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 18, 11, 26, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 17,
                            Price = 80000.0,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 3, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BookedSeats = "A1",
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 18, 8, 26, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 17,
                            Price = 100000.0,
                            RoomId = 2,
                            StartTime = new DateTime(2026, 3, 18, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BookedSeats = "E8",
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 3, 18, 9, 29, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 18,
                            Price = 75000.0,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 3, 18, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id-123",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "user-role-id-456",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id-789",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6237a4c-8143-4acd-9342-de0750ee2f11",
                            Email = "admin@baocinemas.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BAOCINEMAS.COM",
                            NormalizedUserName = "ADMIN@BAOCINEMAS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENjHmoqGqK/ZbigOYAcF+vpUM7ToJjwGPRNH95a1pvNeyniVnmi/KeQnJ6vacURMrQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b426f58-1506-45f9-a2f9-fb6e754e3192",
                            TwoFactorEnabled = false,
                            UserName = "admin@baocinemas.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id-789",
                            RoleId = "admin-role-id-123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Booking", b =>
                {
                    b.HasOne("BAO_Cinemas.Models.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.HasOne("BAO_Cinemas.Models.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Showtime", b =>
                {
                    b.HasOne("BAO_Cinemas.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BAO_Cinemas.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAO_Cinemas.Models.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Cinema", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("BAO_Cinemas.Models.Room", b =>
                {
                    b.Navigation("Showtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
